apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-notes.fullname" . }}
  labels:
    {{- include "my-notes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{.Values.service.nodePort}}
      name: http
  selector:
    {{- include "my-notes.selectorLabels" . | nindent 4 }}
