apiVersion: networking.k8s.io/v1
kind: Ingress

metadata: 
  name: notes-ingress 
  namespace: notes
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules: 
  - host: notes.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service: 
            name: note-service
            port:
              number: 80

