apiVersion: v1
kind: Service

metadata: 
  name: bluegreen-service 
  namespace: test 

spec: 
  type: NodePort
  selector:
    app: test 
    version: v1
  ports:
  - port: 80
    targetPort: 5678
    nodePort: 30080