apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-html
  namespace: demo

data:
  APP_ENV: production
  index.html: | 
    <h1>Test Hello Sunil! From Deployment</h1>
    <p>This page is served using ConfigMap + Deployment</p>
    