services:
  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    environment:
      DB_HOST: db 
      DB_NAME: notesdb 
      DB_USER: notesuser 
      DB_PASSWORD: notessecret
    
  frontend: 
    build: ./frontend
    container_name: nginx-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db 
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notessecret
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 